### ISSUE TITLE
Refactor plugin class name

### ISSUE THREAD

**Issue by camfindlay** [data-govt-nz/ckanext-security#1]
Not a biggie however we could rename the plugin class name to be more vendor neutral and more generically named especially if we start to get further reuse etc.

See https://github.com/data-govt-nz/ckanext-security/blob/master/ckanext/security/plugin.py#L8

`CatalystSecurityPlugin` could become `CkanSecurityPlugin` or something along those lines.

Low priority however just capturing this ticket here to refer back to later. :+1:

**Comment by anotheredward** [comment]
Issue fixed :)
