### ISSUE TITLE
Why is this a plugin and not a pull request to ckan?

### ISSUE THREAD

**Issue by jbothma** [data-govt-nz/ckanext-security#12]
This sounds important.

Why is this a plugin and not a pull request to CKAN?

**Comment by leesdolphin** [comment]
Parts of this code is being pulled into CKAN, however some of the features are more opinionated than should be in CKAN. Additionally maintaining a plugin over the short term is significantly easier than a series of patches to core CKAN.

**Comment by jbothma** [comment]
Awesome. Thanks!

**Comment by camfindlay** [comment]
@jbothma see #2 We'd still be keen to take parts of this module and move into pull requests on core. We may need a hand to prep the pull requests and review them if you're up for helping out?

**Comment by camfindlay** [comment]
I'm going to close this issue but feel free to pick the conversation back up in #2

**Comment by jbothma** [comment]
Oh man I just totally looked past #2 when asking my question. Sorry :)
