### ISSUE TITLE
Supporting ckan 2.10.1

### ISSUE THREAD

**Issue by Nimaj1994** [data-govt-nz/ckanext-security#66]
Hi,
Ckan 2.10.1 has multiple conflict with this plugin, which most of them are related to templates, is there any schedule for updating to this version?

**Comment by markstuart** [comment]
Hi @Nimaj1994, please see #65

**Comment by markstuart** [comment]
Any testing or feedback you can provide would be most appreciated :)

**Comment by Nimaj1994** [comment]
Hi @markstuart , I’ve used your branch and I think it works perfectly and no functionality remained out of work. Good job mate 👍

**Comment by markstuart** [comment]
The CKAN 2.10.x suppport branch has now been merged to master. Thanks for confirming that it worked for you too @Nimaj1994 :)
