### ISSUE TITLE
Security bug on OTP

### ISSUE THREAD

**Issue by maede224** [data-govt-nz/ckanext-security#69]
Hello team,
I have recently found a security bug on Ckanext-Security to bypass OTP feature. Would you please give me an email address to send the report?

**Comment by markstuart** [comment]
Hi @maede224, please forward the details to support@madecurious.com and we will investigate and address it.

**Comment by maede224** [comment]
Hello @markstuart , Thanks for your attention, I emailed the report.

**Comment by markstuart** [comment]
Resolved in 4.1.1
