### ISSUE TITLE
Patch information in README is ambiguous 

### ISSUE THREAD

**Issue by devenson** [data-govt-nz/ckanext-security#7]
I'm having trouble tracking down this required patch:

"Session- and CSRFMiddleware need to be placed at the bottom of the middleware stack. This requires to patch ckan.config.middleware.pylons_app. The patch is currently available in the Catalyst CKAN repository on the catalyst/dia branch, or commit 74f78865 for cherry-pick."

Can you link to the specific commit or provide an inline example of the patch?

**Comment by camfindlay** [comment]
Hey @devenson I think the commit being referred to here is living at https://github.com/data-govt-nz/ckan/commit/74f78865b8825c91d1dfe6b189228f4b975610a3 - a fork of the ckan repo (was once on an internal repo now open sourced).

I've amended the docs to help in the future, many thanks for letting us know about the confusion 👍

**Comment by devenson** [comment]
@camfindlay - I did end up finding it once I realized that the data-govt-nz github account was being referred to as "Catalyst". Thanks for the help.
