### ISSUE TITLE
Bug on new version

### ISSUE THREAD

**Issue by Nimaj1994** [data-govt-nz/ckanext-security#76]
Hi
You’re plugin won’t let me to login on ckan 2.10.4 with error
`ERROR [ckan.lib.webassets_tools] Trying to include unknown asset: <ckanext-geoview/geo-resource-styles_css>`,
Is there any solution?

**Comment by markstuart** [comment]
Are you able to see where in the codebase that CSS file is being included? Without looking into it, I'm unaware of any template overrides in this plugin that would be a cause of this issue. Are you sure this error isn't due to another plugin you have configured in your CKAN installation?

**Comment by Nimaj1994** [comment]
I managed to resolve this problem by changing the content of MANIFEST.in to
`recursive-include ckanext *.html *.json *.yaml *.js *.html *.css *.yml *.config`
.

**Comment by markstuart** [comment]
Do you mean that you edited the MANIFEST.in file in this plugin to the above, and that fixed the issue for you?

**Comment by Nimaj1994** [comment]
@markstuart that is correct.
